### PR TITLE
added Bitcore BTX

### PR DESCRIPTION
**Pull request by dArkjON**
Adding BitCore (BTX)

Website: bitcore.cc
SLIP44=160
COIN_P2PKH_VERSION=3
COIN_P2SH_VERSION=125

### CODE REVIEW

**Comment by dalijolijo** [comment]
@jcrona When do you plan to merge this important pull request?

**Comment by CharlesParent** [comment]
@dalijolijo Hello, we are waiting for SafeT's plugin to be integrated in electron-bitcore project in order to test some BTX transactions before merging this PR

**Comment by dArkjON** [comment]
Hey @CharlesParent 

> @dalijolijo Hello, we are waiting for SafeT's plugin to be integrated in electron-bitcore project in order to test some BTX transactions before merging this PR

Here is the new electrum BTX Git with the safe-T addon : https://github.com/LIMXTEC/electrum-btx

**Comment by dalijolijo** [comment]
@jcrona @CharlesParent @archos-sa 
When do you plan to merge this important pull request? Are your tests successful?

**Comment by jcrona** [comment]
@dalijolijo We are currently testing it. Once everything is validated on our side, it will be merged.

**Comment by jcrona** [comment]
@dalijolijo @dArkjON Thanks for your version of Electrum-BTX ! I confirm it does detect the Safe-T mini and that I am able to send/receive from/to legacy, segwit and native addresses.

However, your current version of Electrum has the same name as the Bitcoin Electrum application, so please change that to something like Electrum-BTX to avoid any confusion (and allow both applications to be installed at the same time).

Also, since we support Linux and MacOS as well as Windows, you need to provide a Linux and a MacOS version of Electrum-BTX in your releases so that we can redirect our users to it (take a look at https://github.com/archos-safe-t/electrum/releases to see what we provide). The MacOS and Windows versions must be signed.

**Comment by dalijolijo** [comment]
@jcrona Thanks for your response. 
The name of our Electrum application is btx-electrum, see here the relevant code lines https://github.com/LIMXTEC/electrum-btx/blob/1f38c663a1a923c4a20f882695e2054a1003ea82/contrib/build-wine/electrum.nsi#L9
Also our Electrum Release is tage with electrum-btx : https://github.com/LIMXTEC/electrum-btx

Yes, we will deliver electrum-btx for Linux and MacOS in near future. Is this a blockIng point for merging this Pull-Request ?

**Comment by jcrona** [comment]
@dalijolijo This change the name of the Windows package, but not the name of the python package (on Linux for instance). Those points are not blocking here, but are required for a distribution on safe-t.io.

**Pull request merged**
